# GitLab CI/CD Pipeline Configuration file
# https://docs.gitlab.com/ee/ci/yaml/
---
stages:
  - test

before_script:
  - pip install tox

python3:
  image: python:3.6
  stage: test
  script: tox -e py3
