# GitLab CI/CD Pipeline Configuration file
# https://docs.gitlab.com/ee/ci/yaml/
---
# environment variables - also set in every service for a job
# NB: setting PGHOST will cause the postgres service to fail
variables:
  SECRET_KEY: "$(openssl rand -base64 32)"
  SQLALCHEMY_DATABASE_TEST_URI: "postgresql://postgres:@postgres/${POSTGRES_DB}"
  REDIS_URL: redis://redis:6379/0
  POSTGRES_DB: portaldb
stages:
  - test
  - deploy

before_script:
  - pip install tox

# test templates
.test_template: &test_definition
  image: python:3.5
  script: tox
  stage: test

.unit_test_template: &unit_test_definition
  <<: *test_definition
  services:
    - postgres:10
    - redis:latest


# test jobs
.unit_tests:
  variables:
    TOXENV: py3
  <<: *unit_test_definition

.unit_tests-python2:
  variables:
    TOXENV: py27
  <<: *unit_test_definition
  image: python:2.7

docgen_test:
  variables:
    TOXENV: docs
  <<: *test_definition

i18n_test_eproms: &i18n_test_eproms_definition
  variables:
    TOXENV: translations
    PERSISTENCE_DIR: eproms
  <<: *unit_test_definition

i18n_test_tnusa: &i18n_test_tnusa_definition
  variables:
    TOXENV: translations
    PERSISTENCE_DIR: gil
  <<: *unit_test_definition


# deploy jobs
i18n_upload_eproms:
  <<: *i18n_test_eproms_definition
  stage: deploy
  script:
    - tox
    - .tox/${TOXENV}/bin/python -m flask translation-upload
  variables:
    FLASK_APP: manage.py

.i18n_upload_tnusa:
  <<: *i18n_test_tnusa_definition
  stage: deploy
  script:
    - tox
    - .tox/${TOXENV}/bin/python -m flask translation-upload
  variables:
    FLASK_APP: manage.py
    SQLALCHEMY_DATABASE_URI: "postgresql://postgres:@postgres/${POSTGRES_DB}"
