# GitLab CI/CD Pipeline Configuration file
# https://docs.gitlab.com/ee/ci/yaml/
---
stages:
  - test

variables:
  SECRET_KEY: "$(openssl rand -base64 32)"
  FLASK_APP: "$(readlink --canonicalize manage.py)"
  SQLALCHEMY_DATABASE_TEST_URI: "postgresql://${PGUSER}:${PGPASSWORD}@postgres/${PGDATABASE}"
  SQLALCHEMY_DATABASE_URI: "postgresql://${PGUSER}:${PGPASSWORD}@postgres/${PGDATABASE}"

  REDIS_URL: redis://redis:6379/0

  PGDATABASE: portaldb
  PGPASSWORD: ""
  PGUSER: postgres
  POSTGRES_DB: portaldb

before_script:
  - pip install tox

# base template
.test_template: &test_definition
  image: python:3.6
  script: tox
  stage: test

# unit test template/overrides
.unit_test_template: &unit_test_definition
  <<: *test_definition
  services:
    - postgres:10
    - redis:latest
  before_script:
    - pip install tox
    # Start celery from tox virtual environment
    - echo "./.tox/${TOXENV}/bin/"
    - ls "./.tox/${TOXENV}/bin/" -l
    - PATH="./.tox/${TOXENV}/bin/"
      celery worker
        --detach
        --app portal.celery_worker.celery
        --loglevel info

unit_tests:
  variables:
    TOXENV: py3
  <<: *unit_test_definition

unit_tests-python2:
  variables:
    TOXENV: py27
  <<: *unit_test_definition
  image: python:2.7

docgen_test:
  variables:
    TOXENV: docs
  <<: *test_definition
