# GitLab CI/CD Pipeline Configuration file
# https://docs.gitlab.com/ee/ci/yaml/
---
stages:
  - test

variables:
  SECRET_KEY: "$(openssl rand -base64 32)"
  FLASK_APP: "$(readlink --canonicalize manage.py)"
  SQLALCHEMY_DATABASE_TEST_URI: "postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}"

  REDIS_URL: redis://redis:6379/0

  PGHOST: postgres
  PGDATABASE: portaldb
  PGPASSWORD: ""
  PGUSER: postgres
  POSTGRES_DB: portaldb


before_script:
  - pip install tox

  # Install dependencies
  - tox --notest


python3:
  variables:
    TOXENV: py3
  image: python:3.6
  stage: test
  script:
    - printenv SQLALCHEMY_DATABASE_TEST_URI
    - echo $SQLALCHEMY_DATABASE_TEST_URI
    - tox

services:
  - postgres:10
  - redis:latest
