# GitLab CI/CD Pipeline Configuration file
# https://docs.gitlab.com/ee/ci/yaml/
---
stages:
  - test

before_script:
  - pip install tox

  - echo $TOXENV
  - printenv TOXENV
  - env
  # Install dependencies
  - tox --notest


python3:
  variables:
    TOXENV: py3
  image: python:3.6
  stage: test
  script:
    - echo $TOXENV
    - printenv TOXENV
    - env
    - tox
