# GitLab CI/CD Pipeline Configuration file
# https://docs.gitlab.com/ee/ci/yaml/
---
stages:
  - test

variables:
  SECRET_KEY: "$(openssl rand -base64 32)"
  FLASK_APP: "$(readlink --canonicalize manage.py)"
  SQLALCHEMY_DATABASE_TEST_URI: "postgresql://${PGUSER}:${PGPASSWORD}@postgres/${PGDATABASE}"
  SQLALCHEMY_DATABASE_URI: "postgresql://${PGUSER}:${PGPASSWORD}@postgres/${PGDATABASE}"

  REDIS_URL: redis://redis:6379/0

  PGDATABASE: portaldb
  PGPASSWORD: ""
  PGUSER: postgres
  POSTGRES_DB: portaldb


before_script:
  - pip install tox

  # Install dependencies
  - tox --notest

  # Start celery from tox virtual environment, if installed
  - if [ -f "./.tox/${TOXENV}/bin/celery" ]; then
      PATH="./.tox/${TOXENV}/bin/"
      celery worker
        --detach
        --app portal.celery_worker.celery
        --loglevel info
      ;
    fi

python3:
  variables:
    TOXENV: py3
  image: python:3.6
  stage: test
  script:
    - tox

python2:
  variables:
    TOXENV: py27
  image: python:2.7
  stage: test
  script:
    - tox

services:
  - postgres:10
  - redis:latest
