---
version: "3.4"
services:
  builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile.build
    volumes:
      - source: ../debian/artifacts
        target: /tmp/artifacts
        type: bind
