# docker-compose production overrides
---
version: "3.4"
services:
  web:
    restart: unless-stopped
    environment:
      # Number of worker processes for handling requests
      # http://docs.gunicorn.org/en/stable/settings.html#workers
      WEB_CONCURRENCY: 4
    healthcheck:
      test: |+
        python -c '
        import os, requests
        resp=requests.get("https://{}/healthcheck".format(os.environ["SERVER_NAME"]))
        resp.raise_for_status()
        exit(0 if resp.json()["status"].lower()=="success" else 1)
        '
      start_period: 2m
      interval: 5m
      timeout: 1m
      retries: 5

  celeryworker:
    restart: unless-stopped
    # Set lower CPU priority to prevent blocking web service
    # remove `nice` prefix of `celery worker` command if necessary on first deploy
    cap_add:
      - SYS_NICE
    command: sh -c '
      env &&
      nice celery worker
        --app portal.celery_worker.celery
        --loglevel debug
      '

  celerybeat:
    restart: unless-stopped

  redis:
    restart: unless-stopped

  db:
    restart: unless-stopped
