---
version: "3.4"
services:
  # Base service; for extension only, not for direct use
  base: &service_base
    image: "${DOCKER_REPOSITORY-uwcirg/}${DOCKER_IMAGE_NAME:-truenth_portal}:${DOCKER_IMAGE_TAG:-latest}"
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - debian_repo="${DEBIAN_REPO:-http://dl.bintray.com/v1/content/uwcirg/${BINTRAY_DEB_REPO:-true_nth}}"
    env_file:
      - ${PORTAL_ENV_FILE:-portal.env}
    environment:
      SECRET_KEY:
      SERVER_NAME:
      PERSISTENCE_DIR: ${PERSISTENCE_DIR:-gil}

      # cross-service defaults
      PGDATABASE: ${PGDATABASE:-portaldb}
      PGHOST: ${PGHOST:-db}
      PGPASSWORD: ${PGPASSWORD:-""}
      PGUSER: ${PGUSER:-postgres}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}

  web:
    <<: *service_base
    ports:
      - target: ${PORT:-8008}
        published: ${EXTERNAL_PORT:-8080}
    depends_on:
      - db
      - redis
      - celeryworker
      - celerybeat
    volumes:
      - source: user-documents
        target: ${FILE_UPLOAD_DIR:-/var/lib/portal/uploads}
        type: volume
      - source: tmp-persistence-data
        target: ${PERSISTENCE_EXCLUSIONS_DIR:-/var/tmp/exclusions}
        type: volume

  celeryworker:
    <<: *service_base
    command: bash -c '
      env &&
      celery worker
        --app portal.celery_worker.celery
        --loglevel debug
      '
    depends_on:
      - redis

  celerybeat:
    <<: *service_base
    command: bash -c '
      env &&
      (wait-for-it --host=redis --port=6379 --strict -- flask set-celery-beat-healthy) &
      wait-for-it --timeout=120 --host=web --port="$$PORT" --strict &&
      celery beat
        --app portal.celery_worker.celery
        --loglevel debug
        --schedule /tmp/celerybeat-schedule.db
        --pidfile /tmp/celerybeat.pid
      '
    depends_on:
      - celeryworker

  redis:
    image: redis
    ports:
      - target: 6379

  db:
    image: postgres:${POSTGRES_VERSION:-10}
    ports:
      - target: 5432
    environment:
      POSTGRES_DB: ${PGDATABASE:-portaldb}
    volumes:
      - source: postgres-data
        target: /var/lib/postgresql/data
        type: volume

volumes:
    postgres-data: {}
    user-documents: {}
    tmp-persistence-data: {}
